language: erlang
otp_release:
  - 20.0
  - 19.3
sudo: false
script: make test
jobs:
  include:
    - stage: deploy
      otp_release: 20.0
      script: skip
      deploy:
        provider: script
        script: "bash -c 'source <(curl -s https://raw.githubusercontent.com/zotonic/hexpub/master/hexpub.sh)'"
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
